"""Public Relay TUI API.

This package re-exports the former ``relay.tui`` module surface so existing tests
and users can continue importing from ``relay.tui`` after the package split.
"""

from .app import RelayTuiApp
from .commands import (
    COMMANDS,
    Command,
    _parse_inline_command,
    _run_active,
    command_by_name,
    filter_commands,
    visible_commands,
)
from .dialogs import FilterInput, SegmentRow, SegmentedControl, SelectDialog, TextEntryDialog, _DIALOG_CSS
from .events import (
    describe_event_for_activity,
    format_turn,
    friendly_provider_error,
    model_identity,
    present_prompt,
)
from .input import PromptInput
from .setup import SetupScreen, persist_role, secrets_set_key, setup_summary
from .stream import STREAM_BUFFER_MAX, STREAM_MAX_LINES
from .theme import (
    ACTOR_BRAIN,
    ACTOR_HANDS,
    ACTOR_YOU,
    C_AMBER,
    C_BG,
    C_CYAN,
    C_DIM,
    C_GREEN,
    C_MAGENTA,
    C_MUTED,
    C_PANEL,
    C_RED,
    C_TXT,
    GREETINGS,
    INPUT_PLACEHOLDERS,
    RELAY_WORDMARK,
    W_BG,
    W_BG_CARD,
    W_BG_DEEP,
    W_BG_RAISED,
    W_BORDER,
    W_RED,
    W_RED_BRIGHT,
    W_TEXT,
    W_TEXT_DIM,
    W_TEXT_MUTED,
    W_WARN,
    _ACTOR_STYLES,
    _ANIM_FPS,
    _COST_PULSE_S,
    _GENERATING_STATES,
    _glitch_thresholds,
    _LED_INTERVAL_S,
    _normalize_block,
    _PLAN_ICON,
    _SPIN_INTERVAL_S,
    _SPINNER_FRAMES,
    _STARTUP_SHORT_S,
    _STATE_PLACEHOLDERS,
    _TRANSITION_SHORT_S,
    glitch_frame,
    pick_greeting,
    pick_placeholder,
    placeholder_for_state,
)

__all__ = [
    "RelayTuiApp",
    "COMMANDS",
    "Command",
    "SelectDialog",
    "TextEntryDialog",
    "SegmentedControl",
    "SetupScreen",
    "setup_summary",
    "persist_role",
    "secrets_set_key",
    "friendly_provider_error",
    "describe_event_for_activity",
    "format_turn",
    "present_prompt",
    "ACTOR_BRAIN",
    "ACTOR_HANDS",
    "ACTOR_YOU",
    "C_CYAN",
    "C_GREEN",
    "C_MAGENTA",
    "GREETINGS",
    "INPUT_PLACEHOLDERS",
    "RELAY_WORDMARK",
    "glitch_frame",
    "model_identity",
    "pick_greeting",
    "pick_placeholder",
    "placeholder_for_state",
    "_normalize_block",
    "_glitch_thresholds",
    "visible_commands",
    "filter_commands",
    "command_by_name",
    "_parse_inline_command",
    "_run_active",
    "PromptInput",
    "FilterInput",
    "SegmentRow",
    "_DIALOG_CSS",
    "STREAM_MAX_LINES",
    "STREAM_BUFFER_MAX",
]
